### ISSUE TITLE
Compiling help: Paths.hx

### ISSUE THREAD

**Issue by Goodbs** [YoshiCrafter29/CodenameEngine#1]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
source/funkin/system/Paths.hx:190: characters 15-17 : Expected )

**My Haxe Version : 4.2.5**
**could it be due to my haxe version?**

**Comment by YoshiCrafter29** [comment]
update your haxe

**Comment by AMNOTSIRVOID** [comment]
??

**Comment by swordcube** [comment]
> update your haxe

yoshi they ARE on the latest
