### ISSUE TITLE
Compiling help: im trying tocompile the engine but this appears

### ISSUE THREAD

**Issue by Bezizeja** [YoshiCrafter29/CodenameEngine#13]
source/funkin/system/XMLSprite.hx:41: characters 15-38 : flixel.FlxSprite has no field doAdditionalMatrixStuff
source/funkin/system/XMLSprite.hx:40: characters 30-53 : Field doAdditionalMatrixStuff is declared 'override' but doesn't override any field
source/funkin/system/Main.hx:104: characters 53-57 : Float should be Int
source/funkin/system/Main.hx:104: characters 53-57 : ... For optional function argument 'UpdateFramerate'
source/funkin/system/Main.hx:104: characters 53-57 : ... For function argument 'child'

- [ ] Windows

**Comment by MemeHoovy** [comment]
use Yoshicrafters fork of flixel `haxelib git flixel-yc29 https://github.com/YoshiCrafter29/flixel`

**Comment by Bezizeja** [comment]
i already did that and still same error

**Comment by MemeHoovy** [comment]
then update it

**Comment by MemeHoovy** [comment]
haxelib update flixel-yc29

**Comment by Bezizeja** [comment]
its is updated

**Comment by MemeHoovy** [comment]
also make sure to update hscript-improved `haxelib update hscript-improved`

**Comment by Bezizeja** [comment]
that is also updated

**Comment by imdumlol** [comment]
me too

**Comment by Bezizeja** [comment]
so nobody knows about this problem?

**Comment by YoshiCrafter29** [comment]
Try running `update.bat`

**Comment by Bezizeja** [comment]
i run that program many times still shows the same error

**Comment by Bezizeja** [comment]
argh im closing this since nobody helps with this problem just send me compiled version on twitter https://twitter.com/bezizeya
