### ISSUE TITLE
Compiling help: won compile

### ISSUE THREAD

**Issue by BlazeTBV** [YoshiCrafter29/CodenameEngine#15]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

source/funkin/cutscenes/MP4Handler.hx:4: characters 8-28 : Type not found : vlc.bitmap.VlcBitmap
source/funkin/cutscenes/MP4Handler.hx:17: characters 20-29 : Type not found : VlcBitmap
source/funkin/game/PlayState.hx:66: lines 66-1453 : ... Defined in this class
source/funkin/cutscenes/VideoCutscene.hx:31: characters 17-33 : funkin.cutscenes.MP4Handler does not have a constructor
source/funkin/cutscenes/VideoCutscene.hx:33: characters 15-26 : funkin.cutscenes.MP4Handler has no field canvasWidth
source/funkin/cutscenes/VideoCutscene.hx:34: characters 15-27 : funkin.cutscenes.MP4Handler has no field canvasHeight
source/funkin/cutscenes/VideoCutscene.hx:41: characters 15-22 : funkin.cutscenes.MP4Handler has no field playMP4

this appears when i try to compile the engine

i ran update.bat, and previous builds work fine

**Comment by TheKitBoi** [comment]
haxelib install hxCodec

**Comment by BlazeTBV** [comment]
its installed tho

**Comment by imdumlol** [comment]
try installing it again

**Comment by imdumlol** [comment]
that works sometimes

**Comment by FoxelTheFennic** [comment]
try pulling the latest commit and run the update.bat file, also make sure you are running `lime test windows` to build '^^

**Comment by YoshiCrafter29** [comment]
Run `update.bat`. You're using the git version of hxCodec while Codename requires the haxelib one.

Might update the engine to support the git version in the near future.
