### ISSUE TITLE
Compiling help: "source/funkin/system/CoolUtil.hx:242: characters 10-14 : Unmatched patterns: NONE"

### ISSUE THREAD

**Issue by biomseed** [YoshiCrafter29/CodenameEngine#16]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.
Every time I run lime build windows, "source/funkin/system/CoolUtil.hx:242: characters 10-14 : Unmatched patterns: NONE" pops up. This just started happening, and it might be related to a recent commit but I'm not too sure. Does this happen for any of you?

**Comment by biomseed** [comment]
When I "fix" the issue by removing the switch statement, I get this. "source/funkin/scripting/Script.hx:44: characters 36-56 : Cannot use abstract as value"

**Comment by biomseed** [comment]
I found out this is because Yoshi is making big changes to their Flixel fork

**Comment by YoshiCrafter29** [comment]
It should work now,

Make sure to run `update.bat` since i updated both hscript-improved and the flixel fork

**Comment by biomseed** [comment]
Thank you
