### ISSUE TITLE
Compiling help: [source/funkin/system/CoolUtil.hx:242: characters 10-14 : Unmatched patterns: NONE]

### ISSUE THREAD

**Issue by Cheese3855195** [YoshiCrafter29/CodenameEngine#21]
[weed]: <> (FILL THIS ISSUE THING OUT AS MUCH AS POSSIBLE)
[weed]: <> (OR ELSE YOUR ISSUE WILL BE LESS LIKELY TO BE SOLVED!)
[weed]: <> (DO NOT POST ABOUT ISSUES FROM OTHER FNF MOD ENGINES! I CANNOT AND PROBABLY WON'T SOLVE THOSE!)
[weed]: <> (GO TO THEIR RESPECTIVE GITHUB ISSUES AND REPORT THEM THERE LOL!)

#### Please check for duplicates or similar compiler issues by filtering for 'compiler help'

[weed]: <> (Put an X in the [ ] thingies to fill out checkbox!)
[weed]: <> (something like [x] pretty much, don't screw up or you will look stupid)

- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

## Please describe your issue. Provide extensive detail and images if possible.

How do I resolve this issue? After I use lime test windows, it displays this error, I am 99% I have everything I need to be installed but I don't know

source/funkin/system/CoolUtil.hx:242: characters 10-14 : Unmatched patterns: NONE

**Comment by SwickTheGreat** [comment]
Run `update.bat`, that should update flixel and should fix your error.

**Comment by biomseed** [comment]
That and get the latest build

**Comment by Cheese3855195** [comment]
It worked but now i got this error
![Capture](https://user-images.githubusercontent.com/62733927/209443977-04773b55-75a0-4fed-97ef-853ba19c2c98.PNG)

**Comment by TheKitBoi** [comment]
get it from here https://github.com/YoshiCrafter29/CodenameEngine/blob/main/buildnumber.txt

**Comment by YoshiCrafter29** [comment]
Use `lime test windows`, not the `buildLatest.bat` file.

Removed it to prevent people from getting confused.
