### ISSUE TITLE
Question: How do you add characters and stages?

### ISSUE THREAD

**Issue by Purpl-ity** [YoshiCrafter29/CodenameEngine#3]
I have tried to add a character and stage but it has failed each time
I dont know if you need to do it in mods folder (Which if you do please explain how it works or add an example somewhere because it is not clear how to do it.)

**Comment by Goodbs** [comment]
this engine has not been released yet. that's why there are so many missing, so use YCE engine for now

**Comment by CaptainKirb49** [comment]
> I have tried to add a character and stage but it has failed each time I dont know if you need to do it in mods folder (Which if you do please explain how it works or add an example somewhere because it is not clear how to do it.)

Yes you can do it in mods, but it needs to be in a specific folder. I will try to make something to document how to do those two specific actions and send it here once I'm done

**Comment by YoshiCrafter29** [comment]
the assets folder is shaped like a mods folder, so just copy one of the character xmls over to your mods folder (for example: assets/data/characters/bf.xml -> mods/introMod/data/characters/bf.xml
same goes for stages
