### ISSUE TITLE
Enhancement: Extra Keys

### ISSUE THREAD

**Issue by BambiGaming2022** [YoshiCrafter29/CodenameEngine#30]
## What is your suggestion, and why should it be implemented?

its will be cool :trollface:

**Comment by MemeHoovy** [comment]
no

**Comment by BambiGaming2022** [comment]
i was joking :trollface:

**Comment by MemeHoovy** [comment]
close this

**Comment by imdumlol** [comment]
yes plz too many people ask for this on engines

**Comment by BombasticTom** [comment]
you can literally just write hscript code

**Comment by BambiGaming2022** [comment]
fine i will close this

**Comment by BambiGaming2022** [comment]
bye bye
