### ISSUE TITLE
Enhancement: colored health for icons

### ISSUE THREAD

**Issue by imdumlol** [YoshiCrafter29/CodenameEngine#31]
like not just red and green icon bar

**Comment by FoxelTheFennic** [comment]
the engine isnt done yet, its planned in the future

**Comment by FoxelTheFennic** [comment]
nevermind then lol
![image](https://user-images.githubusercontent.com/75647306/209733445-e941ec6e-1e7b-4638-99f3-9a4491486603.png)

**Comment by imdumlol** [comment]
eh ok
