### ISSUE TITLE
costom UI

### ISSUE THREAD

**Issue by imdumlol** [YoshiCrafter29/CodenameEngine#32]
how to make sonic.exe UI?

**Comment by SwickTheGreat** [comment]
make a script that modifies the ui??

**Comment by imdumlol** [comment]
but i want with the code ):

**Comment by imdumlol** [comment]
plus the buttons

**Comment by TheKitBoi** [comment]
> but i want with the code ):

https://github.com/duckiewhy/exe-2.5-code/blob/main/source/PlayState.hx

**Comment by imdumlol** [comment]
what line? + will that work?

**Comment by MemeHoovy** [comment]
> what line? + will that work?

find it for yourself, it's pretty much scattered in playstate, and also don't ask people to code for you

**Comment by imdumlol** [comment]
just was asking jeez

**Comment by MemeHoovy** [comment]
> just was asking jeez

sorry, but your issues were just getting annoying

**Comment by imdumlol** [comment]
k

**Comment by SirAxolot** [comment]
this is genuinely the funniest git issue i have ever read
