### ISSUE TITLE
Enhancement: Add to the wiki

### ISSUE THREAD

**Issue by biomseed** [YoshiCrafter29/CodenameEngine#35]
## What is your suggestion, and why should it be implemented?
Document state scripts, note type scripts, and the other things that aren't documented in the wiki.

**Comment by BlazeTBV** [comment]
the wiki is being worked on. its just really early in the stage

**Comment by biomseed** [comment]
> the wiki is being worked on. its just really early in the stage

"the wiki is being worked on" its outdated now

**Comment by WizardMantis441** [comment]
im the one who runs the wiki and tbh i wanna work on documenting things when the v1 of codename releases
i do plan on documenting all of that, more even, but i feel like starting the documentation now would be a bit early if there's not even a stable build out yet yk

**Comment by biomseed** [comment]
you're on the right track (kind of)
