### ISSUE TITLE
Question:  Will lua be implemented in this engine?

### ISSUE THREAD

**Issue by BlazeTBV** [YoshiCrafter29/CodenameEngine#38]
## What is your question?
I dont want to sound like a psych engine stan but i must ask this: will lua for modcharting be implemented or will this engine stay on hscript and that kind of thing

**Comment by biomseed** [comment]
hscript, NO LUA

**Comment by ArdoDev-stupid** [comment]
please close this + lua sucks an this is not psych engine go fuck yourself

**Comment by biomseed** [comment]
> please close this + lua sucks an this is not psych engine go fuck yourself

lua does not suck its just its not hscript

**Comment by YoshiCrafter29** [comment]
[Your answer](https://twitter.com/FNFCodenameEG/status/1597000960492023810?s=20)

**Comment by BlazeTBV** [comment]
> please close this + lua sucks an this is not psych engine go fuck yourself

man i was just asking i dont use twitter

**Comment by MemeHoovy** [comment]
> > please close this + lua sucks an this is not psych engine go fuck yourself
> 
> man i was just asking i dont use twitter

no, lua will not implement

**Comment by BlazeTBV** [comment]
yeah
i figured

> > > please close this + lua sucks an this is not psych engine go fuck yourself
> > 
> > 
> > man i was just asking i dont use twitter
> 
> no, lua will not implemented

**Comment by BlazeTBV** [comment]
![image](https://user-images.githubusercontent.com/111521802/216028549-e96d0c10-edea-4870-83b3-ecdb42cab198.png)

**Comment by OverFlow69** [comment]
> ![image](https://user-images.githubusercontent.com/111521802/216028549-e96d0c10-edea-4870-83b3-ecdb42cab198.png)
> 

Well, that is not your "normal" lua. That's some actually good lua. a.k.a object oriented lua.
