### ISSUE TITLE
Bug Report: you immediately die after loading a song

### ISSUE THREAD

**Issue by BlazeTBV** [YoshiCrafter29/CodenameEngine#39]
- - [x] Windows
- - [ ] Mac
- - [ ] Linux

loading into a game just kills you immediately 

[  15:02:00  |    TRACE    ] source/funkin/system/Main.hx:167: Used lime test windows. Switching into source assets.
[  15:02:00  |    TRACE    ] source/funkin/system/Discord.hx:63: Discord Client initialized
[  15:02:00  |    TRACE    ] source/funkin/system/Discord.hx:12: Discord Client starting...
[  15:02:00  |    TRACE    ] source/funkin/system/Discord.hx:20: Discord Client started.
[  15:02:01  |    ERROR    ] [FLIXEL] Could not find a BitmapData asset with ID 'assets/images/newgrounds_logo.png'.
[  15:02:01  |    TRACE    ] source/funkin/ui/Alphabet.hx:60: Needs refresh!!
[  15:02:05  |    ERROR    ] [FLIXEL] Could not find a BitmapData asset with ID 'assets/images/titlescreen/newgrounds_logo.png'.
[  15:04:13  |    TRACE    ] source/funkin/updating/UpdateUtil.hx:27: v0.1.0
[  15:04:14  |    TRACE    ] source/funkin/updating/UpdateUtil.hx:86: v0.1.2
[  15:04:14  |    TRACE    ] source/funkin/updating/UpdateUtil.hx:86: v0.1.0
[  15:04:22  |    TRACE    ] source/funkin/menus/MainMenuState.hx:186: Credits Menu Selected
[  15:04:37  |    TRACE    ] source/funkin/menus/MainMenuState.hx:182: Freeplay Menu Selected
[  15:04:43  |    ERROR    ] [FLIXEL] Could not find a BitmapData asset with ID 'assets/images/stages/tank/tankBg.png'.
[  15:04:43  |   WARNING   ] Failed to apply XML property: Invalid field:velocity.x on funkin.system.XMLSprite
[  15:04:53  |    ERROR    ] [FLIXEL] Could not find a BitmapData asset with ID 'assets/images/stages/tank/tankBg.png'.
[  15:04:53  |   WARNING   ] Failed to apply XML property: Invalid field:velocity.x on funkin.system.XMLSprite
[  15:05:01  |    ERROR    ] [FLIXEL] Could not find a BitmapData asset with ID 'assets/images/stages/tank/tankBg.png'.
[  15:05:01  |   WARNING   ] Failed to apply XML property: Invalid field:velocity.x on funkin.system.XMLSprite

**Comment by YoshiCrafter29** [comment]
Fixed in eda43a4071c42dd658e32f07dd650493fe0c7bba
