### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by WickedYT** [YoshiCrafter29/CodenameEngine#40]
[weed]: <> (This isn't a place for AMA type questions, if you want to ask any of the devs something, reach out to them on twitter prob )
[weed]: <> (any biz bullshit can go to cameron.taylor.ninja@gmail.com)

## What is your question?

Will YCE charts work with codename? I been very concerned about that and if so then cool

**Comment by lunarcleint** [comment]
yeah, try it

**Comment by SwickTheGreat** [comment]
pretty sure it works with most chart types.

**Comment by WickedYT** [comment]
> yeah, try it

oh ok sick!
