### ISSUE TITLE
Compiling help: Error: Could not find include file "C:/HaxeToolkit/haxe/lib/hxCodec/git/vlc/lib/LibVLCBuild.xml"

### ISSUE THREAD

**Issue by imdumlol** [YoshiCrafter29/CodenameEngine#46]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

idk how to fix

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by biomseed** [comment]
Did you install hxcodec?

**Comment by imdumlol** [comment]
it's fixed
