### ISSUE TITLE
Compiling help: [Did what was told to and still got errors / source/funkin/system/MusicBeatState.hx:89: characters 43-45 : Expected )]

### ISSUE THREAD

**Issue by Megalonumber0ne** [YoshiCrafter29/CodenameEngine#5]
I have everything installed from the original source code for FNF, ran the update.bat and then tried to compile in debug, "Dbeta" and normal compile and all of them gave the below error
source/funkin/system/MusicBeatState.hx:89: characters 43-45 : Expected )
[EDIT]: I tried running the code on windows powershell and the command prompt and CMD crashes instead of giving me the above error, powershell is the one which gives me the error
- [x] Windows
- [ ] Mac
- [ ] Linux
- [ ] HTML5

**Comment by YoshiCrafter29** [comment]
Seems like your Haxe version does not support `obj is Type` statements

Are you sure you're using the latest version available?

If not, you can update to 4.2.5 [here](https://haxe.org/)

**Comment by Megalonumber0ne** [comment]
I just realised that I'm using haxe 4.1.5, thank you!

**Comment by Megalonumber0ne** [comment]
I got a whole slew of errors after updating my version of haxe to 4.2.5 so I'm just going to wait for a full release

**Comment by Megalonumber0ne** [comment]
![image](https://user-images.githubusercontent.com/87905744/206864625-8b7dc825-453c-4db5-b216-c6ab17c30a47.png)

**Comment by YoshiCrafter29** [comment]
Update your lime version.
`haxelib install lime`

**Comment by Megalonumber0ne** [comment]
Alright thank you
