### ISSUE TITLE
Bug Report: The volume of the sound for switching between items in the menus is inconsistent.

### ISSUE THREAD

**Issue by Pigswipe** [YoshiCrafter29/CodenameEngine#51]
### Which target are you using?

[X] Windows
[ ] Linux
[ ] Mac

### Explain your issue

The sound for changing selections in menus seems to get louder and quieter depending on which menu you are in.

It is louder in the main menu, story menu, and any of the options categories than it is in the free play menu, options menu, or controls menu.

https://user-images.githubusercontent.com/50407359/211845702-fb021b71-0c52-428d-93b1-494ac823fd9f.mp4

**Comment by YoshiCrafter29** [comment]
Fixed in 88af9c52a413b3749b25cac91b92a7a6d98a53eb
