### ISSUE TITLE
Bug Report: Custom Week Difficulty is not working

### ISSUE THREAD

**Issue by mystic-akito** [YoshiCrafter29/CodenameEngine#52]
### Which target are you using?

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.

When trying to make a week with 2 difficulties (Hard & Hard Old in my case), it will only use the default difficulties (Easy, Normal & Hard)

The XML of said Week looks like this:
`<week name="WEEK NAME" chars="dad,bf,gf" sprite="week1" difficulties="Hard, Hard Old">`

I'm not sure if I'm doing something wrong, however.

**Comment by 40U538072** [comment]
You can't add custom difficulties from editing an XML file, or through mods folder. You can make it by compiling source code, though that is on Psych Engine for all that I know of. So, I am not sure if it is possible to make custom difficulties using the engine.

**Comment by SrtHero278** [comment]
> I'm not sure if I'm doing something wrong, however.

![image](https://user-images.githubusercontent.com/93018286/212208927-db508dd1-a53d-4238-a57a-6f620c1567c2.png)

nah. for some reason, you have to add a child node to the week.
Like this.
```
<week name="WEEK NAME" chars="dad,bf,gf" sprite="week1">
      <song name="Tutorial" />
      <difficulty name="Hard" />
</week>
```

**Comment by mystic-akito** [comment]
> > I'm not sure if I'm doing something wrong, however.
> 
> ![image](https://user-images.githubusercontent.com/93018286/212208927-db508dd1-a53d-4238-a57a-6f620c1567c2.png)
> 
> nah. for some reason, you have to add a child node to the week. Like this.
> 
> ```
> <week name="WEEK NAME" chars="dad,bf,gf" sprite="week1">
>       <song name="Tutorial" />
>       <difficulty name="Hard" />
> </week>
> ```

Hey, Thank you for helping me with that! But why is it like that? Inside the weeks.xml, it said to do it that way.
