### ISSUE TITLE
Compiling help: it says that there is missing ) on a few functions

### ISSUE THREAD

**Issue by KoutchguestAccount** [YoshiCrafter29/CodenameEngine#53]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
so i was gonna go and compile the game, until it said 2 errors.
source/funkin/system/MusicBeatState.hx:86: characters 43-45 : Expected )
source/funkin/system/MusicBeatState.hx:143: characters 27-29 : Expected )
idk how this shit happened so i'm confused
![proof](https://user-images.githubusercontent.com/83890112/212172351-25f88cfc-6c7b-4972-94f2-8733b75cba1d.png)

**Comment by biomseed** [comment]
download a newer version maybe

**Comment by YoshiCrafter29** [comment]
update your Haxe to the latest
