### ISSUE TITLE
Bug Report: Updating Bug

### ISSUE THREAD

**Issue by ArdoDev-stupid** [YoshiCrafter29/CodenameEngine#56]
In any Actions build, it just updates it to a older version, aka version 1586.

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/212328289-d8d42654-600f-4f58-a826-de305e3d5a22.png)
