### ISSUE TITLE
Note splashes appear twice upon hitting a note sometimes, mostly on hold notes

### ISSUE THREAD

**Issue by biomseed** [YoshiCrafter29/CodenameEngine#57]
This seems to happen at random and this also happens in psych engine in some situations

**Comment by swordcube** [comment]
this probably happens because the chart has stacked notes, which means notes that appear normal but are just...well a bunch of notes stacked on top of each other

**Comment by biomseed** [comment]
> this probably happens because the chart has stacked notes, which means notes that appear normal but are just...well a bunch of notes stacked on top of each other

I don't think so, these are VANILLA fnf charts, and if it was stacked notes, there would be more than 1 combo added

**Comment by YoshiCrafter29** [comment]
fixed
