### ISSUE TITLE
add actions builds

### ISSUE THREAD

**Issue by 504brandon** [YoshiCrafter29/CodenameEngine#6]
i dont want to compile this lmao

**Comment by TheKitBoi** [comment]
lazy + I’ll make a pr workflows if the devs are fine with that

**Comment by 504brandon** [comment]
> lazy + I’ll make a pr workflows if the devs are fine with that

no i just dont have enogh storage LMAO

**Comment by WizardMantis441** [comment]
brandon the engine is not out

**Comment by WizardMantis441** [comment]
it doesnt have a build because it's not done

**Comment by Stilic** [comment]
i will do that on my fork

**Comment by Alexg1247** [comment]
brandon, if i can build it on linux then you can build it ON WINDOWS. THE VERSION THE FUCKING ENGINE WAS MADE FOR.

**Comment by swordcube** [comment]
> > lazy + I’ll make a pr workflows if the devs are fine with that
> 
> no i just dont have enogh storage LMAO

then clear out storage??!?!?!?!

**Comment by FoxelTheFennic** [comment]
> > > lazy + I’ll make a pr workflows if the devs are fine with that
> > 
> > 
> > no i just dont have enogh storage LMAO
> 
> then clear out storage??!?!?!?!

github action builds take up way too much storage, and seeing as how many times yosh commits i dont think its a good idea to run it on commit LMAO

**Comment by FoxelTheFennic** [comment]
just realized this was talking about pc storage and not github storage, oops

**Comment by YoshiCrafter29** [comment]
Added
