### ISSUE TITLE
Compiling help: vlcBitmap and funkin.cutscenes.MP4Handler error

### ISSUE THREAD

**Issue by RamenTheDoodler** [YoshiCrafter29/CodenameEngine#60]
### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### Explain your issue
when i try to run haxelib run lime test windows, this happens
![image](https://user-images.githubusercontent.com/121641643/212766041-dbaa9d62-c485-4584-8624-52c2cec2579d.png)

**Comment by biomseed** [comment]
Perhaps you should read the pinned issue that says in giant letters "READ BEFORE CREATING AN ISSUE".

**Comment by RamenTheDoodler** [comment]
i may be stupid

**Comment by SrtHero278** [comment]
> update your hx codec.

Technically the opposite of that.
```
CodnameEngine-main>haxelib remove hxCodec
CodnameEngine-main>haxelib install hxCodec 2.5.1
```
