### ISSUE TITLE
Bug Report: [F# Key Bug and Options Crash on macOS]

### ISSUE THREAD

**Issue by SIG7Pro** [YoshiCrafter29/CodenameEngine#67]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[X] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

None of the f keys (ex, f1, f2, and f3) don't work in the funny menu that pops up when 7 is pressed. Seems to only happen to me on macOS though. Selecting "Debug Options" in the options menu still crashes the game, and you can highlight stuff in the FPS counter.

**Comment by TumoPlayz** [comment]
mac os be buggin fr
