### ISSUE TITLE
Minimzing The Game Pauses The Song But Once It Refocuses Song Is Still Paused

### ISSUE THREAD

**Issue by SwickTheGreat** [YoshiCrafter29/CodenameEngine#7]
Title Of The Issue Should Explain It.

**Comment by MemeHoovy** [comment]
pretty sure that's intended behaviour

**Comment by MemeHoovy** [comment]
@YoshiCrafter29 close this please, it's another one of those people 🙄

**Comment by SwickTheGreat** [comment]
> @YoshiCrafter29 close this please, it's another one of those people 🙄

a bug is not "indented behavior", let yoshman review the issue.

**Comment by MemeHoovy** [comment]
I doubt so

**Comment by MemeHoovy** [comment]
pretty sure it _is_ intended behaviour

**Comment by MemeHoovy** [comment]
and plus you spelt intended wrong gtfo

**Comment by AnonymousUser351** [comment]
hoovy, its a bug. the song basically halting after you focus the window until you enter and exit the pause menu is a bug.

**Comment by MemeHoovy** [comment]
🤦🏻‍♂️ it's not a BUG you idiots, if the game pauses when the window loses focus, but doesn't unpause when refocusing, it's _INTENDED BEHAVIOUR,_ period

**Comment by AnonymousUser351** [comment]
that's right, you're the bug.

**Comment by MemeHoovy** [comment]
and you're annoying

**Comment by AnonymousUser351** [comment]
dude, you're pretty much the embodiment of somebody who says that Pokémon Scarlet and Violet has no bugs, even after you see all the glitches and performance issues that occurred on the Day 1 patch.

**Comment by MemeHoovy** [comment]
it's not a fucking bug, I know this very well

**Comment by AnonymousUser351** [comment]
if you insist on being wrong, and stubborn: https://youtu.be/TX8bNRP-BcE

**Comment by MemeHoovy** [comment]
ooooohhh, I misinterpreted this whole thing

**Comment by MemeHoovy** [comment]
I thought that meant something else

**Comment by BlazeTBV** [comment]
bruh

**Comment by Stilic** [comment]
@MemeHoovy this wasn't a intended behavior
yosh commented out some code that fixes that in a commit from 3 days
i think he is actually finding a better fix

**Comment by MemeHoovy** [comment]
ik that now

**Comment by MemeHoovy** [comment]
I misinterpreted the whole thing

**Comment by SwickTheGreat** [comment]
closing this, i don't want arguments over a fnf engine.
