### ISSUE TITLE
Compiling help: [fatal error C1083]

### ISSUE THREAD

**Issue by AvalonDrak123** [YoshiCrafter29/CodenameEngine#70]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x ] Windows
[ ] Linux
[ ] Mac

### Explain your issue
when I try to compile the game whit the lime test windows I got something like 
"Error: VlcBitmap.cpp
./src/vlc/bitmap/VlcBitmap.cpp(5): fatal error C1083: Impossible d'ouvrir le fichier include : 'LibVLC.h' : No such file or directory"

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
![Capture d’écran 2023-01-30 213544](https://user-images.githubusercontent.com/98829296/215595224-a960da2c-22cc-4241-b175-16a01b2191ed.png)

**Comment by biomseed** [comment]
![image](https://user-images.githubusercontent.com/73907153/215605925-90ecb7bf-fba1-4c04-a2c9-7441b27fab74.png)

**Comment by AvalonDrak123** [comment]
actually I install everything and yes I already read this but still get this error

**Comment by biomseed** [comment]
> actually I install everything and yes I already read this but still get this error

`haxelib install hxCodec`

**Comment by AvalonDrak123** [comment]
> > actually I install everything and yes I already read this but still get this error
> 
> `haxelib install hxCodec`

sorry but I already done this 4 times before opening this issue but I will try another engine

**Comment by TheKitBoi** [comment]
Did u try
haxelib remove hxCodec
haxelib install hxCodec 2.5.1
