### ISSUE TITLE
Bug Report: Soft-locked after playing Ugh on Story Mode

### ISSUE THREAD

**Issue by BombasticTom** [YoshiCrafter29/CodenameEngine#72]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
After playing Ugh on Story Mode, the game starts playing Ugh cutscene again, and soft-locks you later.

(had to use a third-party video service cuz of the video size) https://streamable.com/e89s4q

**Comment by YoshiCrafter29** [comment]
fixed
