### ISSUE TITLE
Bug Report: [Finishing songs softlocks the game.]

### ISSUE THREAD

**Issue by SIG7Pro** [YoshiCrafter29/CodenameEngine#74]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[ ] Windows
[ ] Linux
[x] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

When finishing a song, mainly modded in songs, the game shows a miniature-countdown and then freezes the game. You can only escape via the editors or by closing the game since you cannot pause. Not sure if this happens for Windows or Linux users though. Mainly happens for me in Freeplay but has happened once in Story Mode. No crashes.

**Comment by TumoPlayz** [comment]
im on linux and this doesnt happen for me
also i thought you said you were on linux

**Comment by YoshiCrafter29** [comment]
Fixed
