### ISSUE TITLE
Bug Report: Problem when trying to use custom gf not using texture-atlas

### ISSUE THREAD

**Issue by superplayhero2** [YoshiCrafter29/CodenameEngine#75]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
If i try to replace gf not using texture-atlas it won't replace gf
But if i use texture-atlas it will replace gf
Which is annoying if i tried to add shading using photoshop or stuff like that
<img width="487" alt="image" src="https://user-images.githubusercontent.com/89041944/217054620-c6487ce6-eff4-4bf5-9a70-e5d4b2797292.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/89041944/217054351-48fd8008-46f3-4e6f-aa03-9c13a6c732dd.png">

**Comment by TheKitBoi** [comment]
The name supposed to be GF_assets

**Comment by superplayhero2** [comment]
> The name supposed to be GF_assets
the name isn't supposed to be GF_assets 
codename engine uses the character png name for it's xmls and the xml is called gf.xml (data/characters/ not to be mistaken for images/characters/)

**Comment by TheKitBoi** [comment]
then make a new char and replace it

**Comment by superplayhero2** [comment]
> then make a new char and replace it
that makes more sense than just trying to replace a character
