### ISSUE TITLE
Unfocusing the game and coming back does a weird thing

### ISSUE THREAD

**Issue by Enderpuff** [YoshiCrafter29/CodenameEngine#8]
When you minimize the game (unfocus it) and come back (focus it) the Instrumental of the song stops playing, but the voices still play. The chart also freezes. If one of the characters where hitting a note at the moment you left, when you come back they still play the animation, but in loop. For some reason, when you pause the game and unpause it the bug fixes itself.

- - [ X] Windows
- - [ ] Mac
- - [ ] Linux

**Comment by MemeHoovy** [comment]
Words from Stilic, this is due to commented out code apparently :/

**Comment by YoshiCrafter29** [comment]
Fixed
