### ISSUE TITLE
Bug Report: github credits bugs

### ISSUE THREAD

**Issue by SirAxolot** [YoshiCrafter29/CodenameEngine#80]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

### 1. When attempting to enter the GitHub credits menu while offline, the game crashes instantly. 
![image](https://user-images.githubusercontent.com/89815386/219884335-566af90f-3238-457e-8c9a-6a4c66f2b56b.png)

### 2. When you exit the GitHub credits, instead of returning to the main menu or the credits selector, it goes to the options menu. (no screenshot available)

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by YoshiCrafter29** [comment]
Fixed
