### ISSUE TITLE
Bug Report: tutorial's broken

### ISSUE THREAD

**Issue by SirAxolot** [YoshiCrafter29/CodenameEngine#82]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[x] Windows
[ ] Linux
[ ] Mac

##### Please check first if your issue haven't already been reported yet.

no comment
![image](https://user-images.githubusercontent.com/89815386/220170991-e01add0f-ded5-4d81-bcb8-8cd2af188c5a.png)

steps to reproduce this bug:
1. literally just enter the tutorial there are two gfs

[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)

**Comment by YoshiCrafter29** [comment]
Fixed
