### ISSUE TITLE
Bug Report: Broken sustain notes

### ISSUE THREAD

**Issue by enderpuff** [YoshiCrafter29/CodenameEngine#84]
Sustain notes are slightly broken, as for texture.

[ X ] Windows
[ X ] Linux
[ ] Mac

The sustain notes do not have their middle part's texture and only the last part, which means they look like this:
![image](https://user-images.githubusercontent.com/96190815/220216535-10e7103e-030b-49fd-b6b2-fad2986614a0.png)
Basically, the middle of sustain notes is invisible

**Comment by YoshiCrafter29** [comment]
Fixed
