### ISSUE TITLE
Bug Report: Notes flipped on Downscroll

### ISSUE THREAD

**Issue by ThatOneIdiotXav** [YoshiCrafter29/CodenameEngine#86]
[weed]: <> (MAKE SURE THAT THE ISSUE IS AS COMPLETE AS POSSIBLE. ISSUES THAT HAVE BARELY ANY INFORMATION OR IS ONLY MADE FOR TROLLING WILL BE INSTANTLY CLOSED.)
[weed]: <> (MAKE SURE TO ADD YOUR TARGET OR IT'LL BE IGNORED!)

### Which target are you using?
[weed]: <> (CHANGE [ ] TO [x] IN FRONT OF YOUR TARGET!)

[X] Windows
[ ] Linux
[ ] Mac

**Build 2374**

##### Please check first if your issue haven't already been reported yet.
[weed]: <> (MAKE SURE TO ADD A SCREENSHOT OF THE CRASH HANDLER, IF AVAILABLE, AND STEPS TO REPRODUCE THE BUG!)
Using downscroll causes the notes' sprites to be flipped.

![image](https://user-images.githubusercontent.com/30373294/220501912-b189cdf4-6961-4d9f-9f85-0f0c43952be9.png)

**Comment by YoshiCrafter29** [comment]
Fixed
